swagger: '2.0'
info:
  title: Category-Service API
  description: Category service API
  version: 1.0.0
host: 'localhost:8888'
schemes:
  - http
basePath: /Eshop
produces:
  - application/json
tags:
  - name: Product
    description: Everything about your Products
  - name: Category
    description: Categories and operations
  - name: Authentication
    description: Operations about user and roles
paths:
  /category:
    get:
      summary: Returns all categories
      description: Returns all existing categories
      tags:
        - Category
      responses:
        '200':
          description: Get all categories
          schema:
            type: array
            items:
              $ref: '#/definitions/category'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create new Category
      description: Create new Category
      tags:
        - Category
      responses:
        '200':
          description: The newly created category
          schema:
            $ref: '#/definitions/category'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/category/{id}':
    get:
      summary: Get category by id
      description: Get a single category by his id
      parameters:
        - name: id
          in: path
          description: ID of category to fetch.
          required: true
          type: number
          format: integer
      tags:
        - Category
      responses:
        '200':
          description: Category with given id.
          schema:
            $ref: '#/definitions/category'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update category by id
      description: Update the category with the given id.
      parameters:
        - name: id
          in: path
          description: ID of category to fetch.
          required: true
          type: number
          format: integer
      tags:
        - Category
      responses:
        '200':
          description: The updated category.
          schema:
            $ref: '#/definitions/category'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Delete category by id
      description: Delete the category with the given id.
      parameters:
        - name: id
          in: path
          description: ID of category to fetch.
          required: true
          type: number
          format: integer
      tags:
        - Category
      responses:
        '200':
          description: Result of deletion.
          schema:
            type: boolean
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  category:
    type: object
    properties:
      id:
        $ref: '#/definitions/ElementId'
      name:
        type: string
        description: Name of category.
  ElementId:
    type: number
    format: integer
    description: Unique identifier representing a specific element
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string